# BacklightdTester
# Autogenerated from man page /usr/share/man/man1/BacklightdTester.1
complete -c BacklightdTester -s a -d 'Description of -a flag'
complete -c BacklightdTester -s b -d 'Description of -b flag \\" Ends the list FILES                \\" File used or …'

