# bm4
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/bm4.1
complete -c bm4 -s D -d 'Define the symbol name to have some value (or NULL )'
complete -c bm4 -s d -d 'Set or unset trace flags'
complete -c bm4 -s E -d 'Set warnings to be fatal'
complete -c bm4 -s G -d 'Disable GNU compatibility mode (see g below)'
complete -c bm4 -s g -d 'Enable GNU compatibility mode'
complete -c bm4 -s I -d 'Add directory dirname to the include path'
complete -c bm4 -s o -d 'Send trace output to filename'
complete -c bm4 -s P -d 'Prefix all built-in macros with m4_'
complete -c bm4 -s s -d 'Output line synchronization directives, suitable for cpp 1'
complete -c bm4 -s t -d 'Turn tracing on for macro'
complete -c bm4 -s U -d 'Undefine the symbol name'

