# bmtool
# Autogenerated from man page /usr/share/man/man1/bmtool.1
complete -c bmtool -s a -d 'Description of -a flag'
complete -c bmtool -s b -d 'Description of -b flag \\" Ends the list FILES                \\" File used or …'

