# bputil
# Autogenerated from man page /usr/share/man/man1/bputil.1
complete -c bputil -s u -d 'Used to specify the username for a user with access to the signing key to aut…'
complete -c bputil -s p -d 'Used to specify the password for a user with access to the signing key to aut…'
complete -c bputil -s v -d 'Specify the APFS Volume Group UUID of the OS intended to have its policy chan…'
complete -c bputil -s l -d 'Enables verbose logging to assist in debugging any issues associated with cha…'
complete -c bputil -s d -d 'Display the detailed contents of the LocalPolicy'
complete -c bputil -s e -d 'Display the detailed contents of the LocalPolicy for every bootable OS instal…'
complete -c bputil -s j -d 'Switch display mode to JSON'
complete -c bputil -s r -d 'Remove macOS and paired recoveryOS local policies for a given Volume Group UU…'
complete -c bputil -s f -d 'Changes security mode to Full Security'
complete -c bputil -s g -d 'Selecting this option will make your system easier to compromise! This change…'
complete -c bputil -s n -d 'Selecting this option will make your system easier to compromise! This change…'
complete -c bputil -s k -d 'Because this option automatically downgrades to Reduced Security mode if not …'
complete -c bputil -s c -d 'Because this option automatically downgrades to Permissive Security mode if n…'
complete -c bputil -s a -d 'Because this option automatically downgrades to Permissive Security mode if n…'
complete -c bputil -s s -d 'Because this option automatically downgrades to Permissive Security mode if n…'
complete -c bputil -s m -d 'Because this option automatically downgrades to Reduced Security mode if not …'

