# bundle-list
# Autogenerated from man page /usr/share/man/man1/bundle-list.1
complete -c bundle-list -l name-only -d 'Print only the name of each gem'
complete -c bundle-list -l paths -d 'Print the path to each gem in the bundle'
complete -c bundle-list -l without-group -d 'Print all gems expect from a group'

