# bundle-binstubs
# Autogenerated from man page /usr/share/man/man1/bundle-binstubs.1
complete -c bundle-binstubs -l force -d 'Overwrite existing binstubs if they exist'
complete -c bundle-binstubs -l path -d 'The location to install the specified binstubs to.  This defaults to bin'
complete -c bundle-binstubs -l standalone -d 'Makes binstubs that can work without depending on Rubygems or Bundler at runt…'

