# bundle-add
# Autogenerated from man page /usr/share/man/man1/bundle-add.1
complete -c bundle-add -l version -s v -d 'Specify version requirements(s) for the added gem'
complete -c bundle-add -l group -s g -d 'Specify the group(s) for the added gem'
complete -c bundle-add -l source -s s -d 'Specify the source for the added gem'
complete -c bundle-add -l skip-install -d 'Adds the gem to the Gemfile but does not install it'
complete -c bundle-add -l optimistic -d 'Adds optimistic declaration of version '

