# cargo-login
# Autogenerated from man page /opt/homebrew/share/man/man1/cargo-login.1
complete -c cargo-login -l registry
complete -c cargo-login -s v
complete -c cargo-login -l verbose
complete -c cargo-login -s q
complete -c cargo-login -l quiet
complete -c cargo-login -l color
complete -c cargo-login -l config
complete -c cargo-login -s C
complete -c cargo-login -s h
complete -c cargo-login -l help
complete -c cargo-login -s Z

