# cargo-info
# Autogenerated from man page /opt/homebrew/share/man/man1/cargo-info.1
complete -c cargo-info -l index
complete -c cargo-info -l registry
complete -c cargo-info -s v
complete -c cargo-info -l verbose
complete -c cargo-info -s q
complete -c cargo-info -l quiet
complete -c cargo-info -l color
complete -c cargo-info -l locked
complete -c cargo-info -l offline
complete -c cargo-info -l frozen
complete -c cargo-info -l config
complete -c cargo-info -s C
complete -c cargo-info -s h
complete -c cargo-info -l help
complete -c cargo-info -s Z

