# cryptexctl-uninstall
# Autogenerated from man page /usr/share/man/man1/cryptexctl-uninstall.1
complete -c cryptexctl-uninstall -s i -d 'Force physical uninstalltion to happen immediately if possible'

