# cscheck
# Autogenerated from man page /usr/share/man/man1/cscheck.1
complete -c cscheck -s a -d 'Description of -a flag'
complete -c cscheck -s b -d 'Description of -b flag \\" Ends the list FILES                \\" File used or …'

