# cxattr
# Autogenerated from man page /usr/share/man/man1/cxattr.1
complete -c cxattr -s a -d 'Description of -a flag'
complete -c cxattr -s b -d 'Description of -b flag \\" Ends the list FILES                \\" File used or …'

