# dyld
# Autogenerated from man page /usr/share/man/man1/dyld.1
complete -c dyld -s L -d 'option to  otool (1) to discover the frameworks and shared libraries that the…'
complete -c dyld -o 'u->' -o 'd->'

