# fileurltool
# Autogenerated from man page /usr/share/man/man1/fileurltool.1
complete -c fileurltool -o by-path -d 'Create a file-path URL which uses the file path string'
complete -c fileurltool -o by-ref -d 'Create a file-reference URL before calling the API'
complete -c fileurltool -o cf1 -d 'Use\\ CFURLCopyResourcePropertyForKey / CFURLSetResourcePropertyForKey API'
complete -c fileurltool -o cfm -d 'Use CFURLCopyResourcePropertiesForKeys / CFURLSetResourcePropertiesForKeys API'
complete -c fileurltool -o ns1 -d 'Use NSURL\'s  getResourceValue:forKey:error: and setResourceValue:forKey:error…'
complete -c fileurltool -o nsm -d 'Use NSURL\'s resourceValuesForKeys:error: and setResourceValues:error: API El'

