# fuser
# Autogenerated from man page /usr/share/man/man1/fuser.1
complete -c fuser -s c -d 'The file is treated as a mount point and the utility shall report on any file…'
complete -c fuser -s f -d 'The report shall be only for the named files'
complete -c fuser -s u -d 'The user name, in parentheses, associated with each process ID written to sta…'

