# gh-auth-logout
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-auth-logout.1
complete -c gh-auth-logout -s h -l hostname -d 'The hostname of the GitHub instance to log out of'
complete -c gh-auth-logout -s u -l user -d 'The account to log out of EXIT CODES 0: Successful execution 1: Error 2: Comm…'

