# gh-auth-setup-git
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-auth-setup-git.1
complete -c gh-auth-setup-git -s f -l force -d 'Force setup even if the host is not known'
complete -c gh-auth-setup-git -s h -l hostname -d 'The hostname to configure git for EXIT CODES 0: Successful execution 1: Error…'

