# gh-auth-status
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-auth-status.1
complete -c gh-auth-status -s a -l active -d 'Display the active account only'
complete -c gh-auth-status -s h -l hostname -d 'Check only a specific hostname\'s auth status'
complete -c gh-auth-status -s t -l show-token -d 'Display the auth token EXIT CODES 0: Successful execution 1: Error 2: Command…'

