# gh-auth-token
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-auth-token.1
complete -c gh-auth-token -s h -l hostname -d 'The hostname of the GitHub instance authenticated with'
complete -c gh-auth-token -s u -l user -d 'The account to output the token for EXIT CODES 0: Successful execution 1: Err…'

