# gh-alias-import
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-alias-import.1
complete -c gh-alias-import -l clobber -d 'Overwrite existing aliases of the same name EXIT CODES 0: Successful executio…'

