# gh-api
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-api.1
complete -c gh-api -l cache -d 'Cache the response, e. g.  "3600s", "60m", "1h"'
complete -c gh-api -s F -l field -d 'Add a typed parameter in key=value format'
complete -c gh-api -s H -l header -d 'Add a HTTP request header in key:value format'
complete -c gh-api -l hostname -d 'The GitHub hostname for the request (default "github. com")'
complete -c gh-api -s i -l include -d 'Include HTTP response status line and headers in the output'
complete -c gh-api -l input -d 'The file to use as body for the HTTP request (use "-" to read from standard i…'
complete -c gh-api -s q -l jq -d 'Query to select values from the response using jq syntax'
complete -c gh-api -s X -l method -d 'The HTTP method for the request'
complete -c gh-api -l paginate -d 'Make additional HTTP requests to fetch all pages of results'
complete -c gh-api -s p -l preview -d 'GitHub API preview names to request (without the "-preview" suffix)'
complete -c gh-api -s f -l raw-field -d 'Add a string parameter in key=value format'
complete -c gh-api -l silent -d 'Do not print the response body'
complete -c gh-api -l slurp -d 'Use with "--paginate" to return an array of all pages of either JSON arrays o…'
complete -c gh-api -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-api -o F/--field -d 'request method to POST'
complete -c gh-api -l verbose -d 'Include full HTTP request and response in the output EXIT CODES 0: Successful…'

