# gh-alias-set
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-alias-set.1
complete -c gh-alias-set -l clobber -d 'Overwrite existing aliases of the same name'
complete -c gh-alias-set -s s -l shell -d 'Declare an alias to be passed through a shell interpreter EXIT CODES 0: Succe…'

