# gh-auth-switch
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-auth-switch.1
complete -c gh-auth-switch -s h -l hostname -d 'The hostname of the GitHub instance to switch account for'
complete -c gh-auth-switch -s u -l user -d 'The account to switch to EXIT CODES 0: Successful execution 1: Error 2: Comma…'

