# gh-auth-login
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-auth-login.1
complete -c gh-auth-login -s p -l git-protocol -d 'The protocol to use for git operations on this host: {ssh|https}'
complete -c gh-auth-login -s h -l hostname -d 'The hostname of the GitHub instance to authenticate with'
complete -c gh-auth-login -l insecure-storage -d 'Save authentication credentials in plain text instead of credential store'
complete -c gh-auth-login -s s -l scopes -d 'Additional authentication scopes to request'
complete -c gh-auth-login -l skip-ssh-key -d 'Skip generate/upload SSH key prompt'
complete -c gh-auth-login -s w -l web -d 'Open a browser to authenticate'
complete -c gh-auth-login -l with-token -d 'Read token from standard input EXIT CODES 0: Successful execution 1: Error 2:…'

