# gh-auth-refresh
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-auth-refresh.1
complete -c gh-auth-refresh -s h -l hostname -d 'The GitHub host to use for authentication'
complete -c gh-auth-refresh -l insecure-storage -d 'Save authentication credentials in plain text instead of credential store'
complete -c gh-auth-refresh -s r -l remove-scopes -d 'Authentication scopes to remove from gh'
complete -c gh-auth-refresh -l reset-scopes -d 'Reset authentication scopes to the default minimum set of scopes'
complete -c gh-auth-refresh -s s -l scopes -d 'Additional authentication scopes for gh to have EXIT CODES 0: Successful exec…'

