# gh-attestation-trusted-root
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-attestation-trusted-root.1
complete -c gh-attestation-trusted-root -l hostname -d 'Configure host to use'
complete -c gh-attestation-trusted-root -l tuf-root -d 'Path to the TUF root. json file on disk'
complete -c gh-attestation-trusted-root -l tuf-url -d 'URL to the TUF repository mirror'
complete -c gh-attestation-trusted-root -l verify-only -d 'Don\'t output trusted_root'

