# gh-attestation-download
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-attestation-download.1
complete -c gh-attestation-download -s d -l digest-alg -d 'The algorithm used to compute a digest of the artifact: {sha256|sha512}'
complete -c gh-attestation-download -l hostname -d 'Configure host to use'
complete -c gh-attestation-download -s L -l limit -d 'Maximum number of attestations to fetch'
complete -c gh-attestation-download -s o -l owner -d 'a GitHub organization to scope attestation lookup by'
complete -c gh-attestation-download -l predicate-type -d 'Filter attestations by provided predicate type'
complete -c gh-attestation-download -s R -l repo -d 'Repository name in the format / EXIT CODES 0: Successful execution 1: Error 2…'

