# gh-config-set
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-config-set.1
complete -c gh-config-set -s h -l host -d 'Set per-host setting EXIT CODES 0: Successful execution 1: Error 2: Command c…'

