# gh-completion
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-completion.1
complete -c gh-completion -s s -l shell -d 'Shell type: {bash|zsh|fish|powershell} EXIT CODES 0: Successful execution 1: …'

