# gh-cache
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-cache.1
complete -c gh-cache -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

