# gh-codespace-rebuild
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-codespace-rebuild.1
complete -c gh-codespace-rebuild -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-rebuild -l full -d 'perform a full rebuild'
complete -c gh-codespace-rebuild -s R -l repo -d 'Filter codespace selection by repository name (user/repo)'
complete -c gh-codespace-rebuild -l repo-owner -d 'Filter codespace selection by repository owner (username or org) EXIT CODES 0…'

