# gh-codespace-ports-visibility
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-codespace-ports-visibility.1
complete -c gh-codespace-ports-visibility -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-ports-visibility -s R -l repo -d 'Filter codespace selection by repository name (user/repo)'
complete -c gh-codespace-ports-visibility -l repo-owner -d 'Filter codespace selection by repository owner (username or org) EXIT CODES 0…'

