# gh-config-get
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-config-get.1
complete -c gh-config-get -s h -l host -d 'Get per-host setting EXIT CODES 0: Successful execution 1: Error 2: Command c…'

