# gh-extension-browse
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-extension-browse.1
complete -c gh-extension-browse -l debug -d 'log to /tmp/extBrowse-*'
complete -c gh-extension-browse -s s -l single-column -d 'Render TUI with only one column of text EXIT CODES 0: Successful execution 1:…'

