# gh-extension-upgrade
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-extension-upgrade.1
complete -c gh-extension-upgrade -l all -d 'Upgrade all extensions'
complete -c gh-extension-upgrade -l dry-run -d 'Only display upgrades'
complete -c gh-extension-upgrade -l force -d 'Force upgrade extension EXIT CODES 0: Successful execution 1: Error 2: Comman…'

