# gh-gist-list
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-gist-list.1
complete -c gh-gist-list -l filter -d 'Filter gists using a regular expression'
complete -c gh-gist-list -l include-content -d 'Include gists\' file content when filtering'
complete -c gh-gist-list -s L -l limit -d 'Maximum number of gists to fetch'
complete -c gh-gist-list -l public -d 'Show only public gists'
complete -c gh-gist-list -l secret -d 'Show only secret gists ALIASES gh gist ls EXIT CODES 0: Successful execution …'

