# gh-gpg-key-delete
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-gpg-key-delete.1
complete -c gh-gpg-key-delete -s y -l yes -d 'Skip the confirmation prompt EXIT CODES 0: Successful execution 1: Error 2: C…'

