# gh-gist-edit
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-gist-edit.1
complete -c gh-gist-edit -s a -l add -d 'Add a new file to the gist'
complete -c gh-gist-edit -s d -l desc -d 'New description for the gist'
complete -c gh-gist-edit -s f -l filename -d 'Select a file to edit'
complete -c gh-gist-edit -s r -l remove -d 'Remove a file from the gist EXIT CODES 0: Successful execution 1: Error 2: Co…'

