# gh-gpg-key-add
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-gpg-key-add.1
complete -c gh-gpg-key-add -s t -l title -d 'Title for the new key EXIT CODES 0: Successful execution 1: Error 2: Command …'

