# gh-issue-transfer
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-issue-transfer.1
complete -c gh-issue-transfer -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

