# gh-issue-reopen
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-issue-reopen.1
complete -c gh-issue-reopen -s c -l comment -d 'Add a reopening comment OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-issue-reopen -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

