# gh-issue-status
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-issue-status.1
complete -c gh-issue-status -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-issue-status -l json -d 'Output JSON with the specified fields'
complete -c gh-issue-status -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" OPTIONS INHE…'
complete -c gh-issue-status -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format JSON FIELDS assi…'

