# gh-issue-close
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-issue-close.1
complete -c gh-issue-close -s c -l comment -d 'Leave a closing comment'
complete -c gh-issue-close -s r -l reason -d 'Reason for closing: {completed|not planned} OPTIONS INHERITED FROM PARENT COM…'
complete -c gh-issue-close -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

