# gh-issue-unlock
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-issue-unlock.1
complete -c gh-issue-unlock -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

