# gh-issue-delete
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-issue-delete.1
complete -c gh-issue-delete -l yes -d 'confirm deletion without prompting OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-issue-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

