# gh-issue-pin
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-issue-pin.1
complete -c gh-issue-pin -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

