# gh-label
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-label.1
complete -c gh-label -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

