# gh-org-list
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-org-list.1
complete -c gh-org-list -s L -l limit -d 'Maximum number of organizations to list ALIASES gh org ls EXIT CODES 0: Succe…'

