# gh-project-mark-template
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-mark-template.1
complete -c gh-project-mark-template -l format -d 'Output format: {json}'
complete -c gh-project-mark-template -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-mark-template -l owner -d 'Login of the org owner'
complete -c gh-project-mark-template -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-project-mark-template -l undo -d 'Unmark the project as a template'

