# gh-project-item-edit
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-item-edit.1
complete -c gh-project-item-edit -l body -d 'Body of the draft issue item'
complete -c gh-project-item-edit -l clear -d 'Remove field value'
complete -c gh-project-item-edit -l date -d 'Date value for the field (YYYY-MM-DD)'
complete -c gh-project-item-edit -l field-id -d 'ID of the field to update'
complete -c gh-project-item-edit -l format -d 'Output format: {json}'
complete -c gh-project-item-edit -l id -d 'ID of the item to edit'
complete -c gh-project-item-edit -l iteration-id -d 'ID of the iteration value to set on the field'
complete -c gh-project-item-edit -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-item-edit -l number -d 'Number value for the field'
complete -c gh-project-item-edit -l project-id -d 'ID of the project to which the field belongs to'
complete -c gh-project-item-edit -l single-select-option-id -d 'ID of the single select option value to set on the field'
complete -c gh-project-item-edit -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-project-item-edit -l text -d 'Text value for the field'
complete -c gh-project-item-edit -l title -d 'Title of the draft issue item EXIT CODES 0: Successful execution 1: Error 2: …'

