# gh-project-link
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-link.1
complete -c gh-project-link -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-link -s R -l repo -d 'The repository to be linked to this project'
complete -c gh-project-link -s T -l team -d 'The team to be linked to this project EXIT CODES 0: Successful execution 1: E…'

