# gh-project-field-create
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-field-create.1
complete -c gh-project-field-create -l data-type -d 'DataType of the new field. : {TEXT|SINGLE_SELECT|DATE|NUMBER}'
complete -c gh-project-field-create -l format -d 'Output format: {json}'
complete -c gh-project-field-create -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-field-create -l name -d 'Name of the new field'
complete -c gh-project-field-create -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-field-create -l single-select-options -d 'Options for SINGLE_SELECT data type'
complete -c gh-project-field-create -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" EXIT CODES 0…'

