# gh-pr-close
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-pr-close.1
complete -c gh-pr-close -s c -l comment -d 'Leave a closing comment'
complete -c gh-pr-close -s d -l delete-branch -d 'Delete the local and remote branch after close OPTIONS INHERITED FROM PARENT …'
complete -c gh-pr-close -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

