# gh-pr-update-branch
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-pr-update-branch.1
complete -c gh-pr-update-branch -l rebase -d 'Update PR branch by rebasing on top of latest base branch OPTIONS INHERITED F…'
complete -c gh-pr-update-branch -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

