# gh-project-field-delete
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-field-delete.1
complete -c gh-project-field-delete -l format -d 'Output format: {json}'
complete -c gh-project-field-delete -l id -d 'ID of the field to delete'
complete -c gh-project-field-delete -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-field-delete -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" EXIT CODES 0…'

