# gh-project-item-delete
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-item-delete.1
complete -c gh-project-item-delete -l format -d 'Output format: {json}'
complete -c gh-project-item-delete -l id -d 'ID of the item to delete'
complete -c gh-project-item-delete -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-item-delete -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-item-delete -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" EXIT CODES 0…'

