# gh-project-item-archive
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-item-archive.1
complete -c gh-project-item-archive -l format -d 'Output format: {json}'
complete -c gh-project-item-archive -l id -d 'ID of the item to archive'
complete -c gh-project-item-archive -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-item-archive -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-item-archive -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-project-item-archive -l undo -d 'Unarchive an item EXIT CODES 0: Successful execution 1: Error 2: Command canc…'

