# gh-project-field-list
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-field-list.1
complete -c gh-project-field-list -l format -d 'Output format: {json}'
complete -c gh-project-field-list -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-field-list -s L -l limit -d 'Maximum number of fields to fetch'
complete -c gh-project-field-list -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-field-list -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" EXIT CODES 0…'

