# gh-project-item-create
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-item-create.1
complete -c gh-project-item-create -l body -d 'Body for the draft issue'
complete -c gh-project-item-create -l format -d 'Output format: {json}'
complete -c gh-project-item-create -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-item-create -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-item-create -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-project-item-create -l title -d 'Title for the draft issue EXIT CODES 0: Successful execution 1: Error 2: Comm…'

