# gh-pr-ready
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-pr-ready.1
complete -c gh-pr-ready -l undo -d 'Convert a pull request to "draft" OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-ready -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

