# gh-pr-checks
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-pr-checks.1
complete -c gh-pr-checks -l fail-fast -d 'Exit watch mode on first check failure'
complete -c gh-pr-checks -s i -l interval -d 'Refresh interval in seconds when using --watch flag'
complete -c gh-pr-checks -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-pr-checks -l json -d 'Output JSON with the specified fields'
complete -c gh-pr-checks -l required -d 'Only show checks that are required'
complete -c gh-pr-checks -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-pr-checks -l watch -d 'Watch checks until they finish'
complete -c gh-pr-checks -s w -l web -d 'Open the web browser to show details about checks OPTIONS INHERITED FROM PARE…'
complete -c gh-pr-checks -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format JSON FIELDS buck…'

