# gh-project-edit
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-edit.1
complete -c gh-project-edit -s d -l description -d 'New description of the project'
complete -c gh-project-edit -l format -d 'Output format: {json}'
complete -c gh-project-edit -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-edit -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-edit -l readme -d 'New readme for the project'
complete -c gh-project-edit -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-project-edit -l title -d 'New title for the project'
complete -c gh-project-edit -l visibility -d 'Change project visibility: {PUBLIC|PRIVATE} EXIT CODES 0: Successful executio…'

