# gh-project-item-add
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-item-add.1
complete -c gh-project-item-add -l format -d 'Output format: {json}'
complete -c gh-project-item-add -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-item-add -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-item-add -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-project-item-add -l url -d 'URL of the issue or pull request to add to the project EXIT CODES 0: Successf…'

