# gh-pr-status
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-pr-status.1
complete -c gh-pr-status -s c -l conflict-status -d 'Display the merge conflict status of each pull request'
complete -c gh-pr-status -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-pr-status -l json -d 'Output JSON with the specified fields'
complete -c gh-pr-status -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" OPTIONS INHE…'
complete -c gh-pr-status -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format JSON FIELDS addi…'

