# gh-pr-reopen
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-pr-reopen.1
complete -c gh-pr-reopen -s c -l comment -d 'Add a reopening comment OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-reopen -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

