# gh-project-close
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-project-close.1
complete -c gh-project-close -l format -d 'Output format: {json}'
complete -c gh-project-close -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-project-close -l owner -d 'Login of the owner.  Use "@me" for the current user'
complete -c gh-project-close -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting"'
complete -c gh-project-close -l undo -d 'Reopen a closed project EXIT CODES 0: Successful execution 1: Error 2: Comman…'

