# gh-repo-deploy-key-delete
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-repo-deploy-key-delete.1
complete -c gh-repo-deploy-key-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

