# gh-ruleset-check
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-ruleset-check.1
complete -c gh-ruleset-check -l default -d 'Check rules on default branch'
complete -c gh-ruleset-check -s w -l web -d 'Open the branch rules page in a web browser OPTIONS INHERITED FROM PARENT COM…'
complete -c gh-ruleset-check -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

