# gh-repo-delete
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-repo-delete.1
complete -c gh-repo-delete -l yes -d 'confirm deletion without prompting EXIT CODES 0: Successful execution 1: Erro…'

