# gh-repo-unarchive
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-repo-unarchive.1
complete -c gh-repo-unarchive -s y -l yes -d 'Skip the confirmation prompt EXIT CODES 0: Successful execution 1: Error 2: C…'

