# gh-repo-sync
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-repo-sync.1
complete -c gh-repo-sync -s b -l branch -d 'Branch to sync (default [default branch])'
complete -c gh-repo-sync -l force -d 'Hard reset the branch of the destination repository to match the source repos…'
complete -c gh-repo-sync -s s -l source -d 'Source repository EXIT CODES 0: Successful execution 1: Error 2: Command canc…'

