# gh-release
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-release.1
complete -c gh-release -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

