# gh-repo-clone
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-repo-clone.1
complete -c gh-repo-clone -s u -l upstream-remote-name -d 'Upstream remote name when cloning a fork EXIT CODES 0: Successful execution 1…'

