# gh-repo-autolink
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-repo-autolink.1
complete -c gh-repo-autolink -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

