# gh-ruleset-list
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-ruleset-list.1
complete -c gh-ruleset-list -s L -l limit -d 'Maximum number of rulesets to list'
complete -c gh-ruleset-list -s o -l org -d 'List organization-wide rulesets for the provided organization'
complete -c gh-ruleset-list -s p -l parents -d 'Whether to include rulesets configured at higher levels that also apply'
complete -c gh-ruleset-list -s w -l web -d 'Open the list of rulesets in the web browser OPTIONS INHERITED FROM PARENT CO…'
complete -c gh-ruleset-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format ALIASES gh rs ls…'

