# gh-repo-set-default
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-repo-set-default.1
complete -c gh-repo-set-default -s u -l unset -d 'unset the current default repository'
complete -c gh-repo-set-default -s v -l view -d 'view the current default repository EXIT CODES 0: Successful execution 1: Err…'

