# gh-release-delete-asset
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-release-delete-asset.1
complete -c gh-release-delete-asset -s y -l yes -d 'Skip the confirmation prompt OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-release-delete-asset -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

