# gh-release-edit
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-release-edit.1
complete -c gh-release-edit -l discussion-category -d 'Start a discussion in the specified category when publishing a draft'
complete -c gh-release-edit -l draft -d 'Save the release as a draft instead of publishing it'
complete -c gh-release-edit -l latest -d 'Explicitly mark the release as "Latest"'
complete -c gh-release-edit -s n -l notes -d 'Release notes'
complete -c gh-release-edit -s F -l notes-file -d 'Read release notes from file (use "-" to read from standard input)'
complete -c gh-release-edit -l prerelease -d 'Mark the release as a prerelease'
complete -c gh-release-edit -l tag -d 'The name of the tag'
complete -c gh-release-edit -l target -d 'Target branch or full commit SHA (default [main branch])'
complete -c gh-release-edit -s t -l title -d 'Release title'
complete -c gh-release-edit -l verify-tag -d 'Abort in case the git tag doesn\'t already exist in the remote repository OPTI…'
complete -c gh-release-edit -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

