# gh-release-delete
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-release-delete.1
complete -c gh-release-delete -l cleanup-tag -d 'Delete the specified tag in addition to its release'
complete -c gh-release-delete -s y -l yes -d 'Skip the confirmation prompt OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-release-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

