# gh-release-list
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-release-list.1
complete -c gh-release-list -l exclude-drafts -d 'Exclude draft releases'
complete -c gh-release-list -l exclude-pre-releases -d 'Exclude pre-releases'
complete -c gh-release-list -s q -l jq -d 'Filter JSON output using a jq expression'
complete -c gh-release-list -l json -d 'Output JSON with the specified fields'
complete -c gh-release-list -s L -l limit -d 'Maximum number of items to fetch'
complete -c gh-release-list -s O -l order -d 'Order of releases returned: {asc|desc}'
complete -c gh-release-list -s t -l template -d 'Format JSON output using a Go template; see "gh help formatting" OPTIONS INHE…'
complete -c gh-release-list -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format ALIASES gh relea…'

