# gh-repo-deploy-key
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-repo-deploy-key.1
complete -c gh-repo-deploy-key -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

