# gh-ssh-key-add
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-ssh-key-add.1
complete -c gh-ssh-key-add -s t -l title -d 'Title for the new key'
complete -c gh-ssh-key-add -l type -d 'Type of the ssh key: {authentication|signing} EXIT CODES 0: Successful execut…'

