# gh-secret
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-secret.1
complete -c gh-secret -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

