# gh-status
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-status.1
complete -c gh-status -s e -l exclude -d 'Comma separated list of repos to exclude in owner/name format'
complete -c gh-status -s o -l org -d 'Report status within an organization EXIT CODES 0: Successful execution 1: Er…'

