# gh-variable
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-variable.1
complete -c gh-variable -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

