# gh-workflow-enable
# Autogenerated from man page /opt/homebrew/share/man/man1/gh-workflow-enable.1
complete -c gh-workflow-enable -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

