# git-verify-tag
# Autogenerated from man page /opt/homebrew/share/man/man1/git-verify-tag.1
complete -c git-verify-tag -l raw -d 'Print the raw gpg status output to standard error instead of the normal human…'
complete -c git-verify-tag -s v -l verbose -d 'Print the contents of the tag object before validating it'

