# git-check-mailmap
# Autogenerated from man page /opt/homebrew/share/man/man1/git-check-mailmap.1
complete -c git-check-mailmap -l stdin -d 'Read contacts, one per line, from the standard input after exhausting contact…'
complete -c git-check-mailmap -l mailmap-file -d 'In addition to any configured mailmap files, read the specified mailmap file'
complete -c git-check-mailmap -l mailmap-blob -d 'Like --mailmap-file, but consider the value as a reference to a blob in the r…'

