# git-var
# Autogenerated from man page /opt/homebrew/share/man/man1/git-var.1
complete -c git-var -s l -d 'Display the logical variables'
complete -c git-var -l nofork -d '$GIT_EDITOR environment variable, then core'
complete -c git-var -s i -d 'GIT_EDITOR, the value is meant to be interpreted by the shell when it is used'

