# git-refs
# Autogenerated from man page /opt/homebrew/share/man/man1/git-refs.1
complete -c git-refs -l ref-format -d 'The ref format to migrate the ref store to.  Can be one of: . sp'
complete -c git-refs -l dry-run -d 'Perform the migration, but do not modify the repository'
complete -c git-refs -l strict -d 'Enable stricter error checking'
complete -c git-refs -l verbose -d 'When verifying the reference database consistency, be chatty'

