# heif-thumbnailer
# Autogenerated from man page /opt/homebrew/share/man/man1/heif-thumbnailer.1
complete -c heif-thumbnailer -s s -d 'Defines the maximum width and height of the thumbnail to generate'

