# hmac256
# Autogenerated from man page /opt/homebrew/share/man/man1/hmac256.1
complete -c hmac256 -l binary -d 'Print the MAC as a binary string'
complete -c hmac256 -l version -d 'Print version of the program and exit.  SEE ALSO sha256sum(1)'

