# icqctl
# Autogenerated from man page /usr/share/man/man1/icqctl.1
complete -c icqctl -s a -d 'Description of -a flag'
complete -c icqctl -s b -d 'Description of -b flag \\" Ends the list FILES                \\" File used or …'

