# intelligentroutingd
# Autogenerated from man page /usr/share/man/man8/intelligentroutingd.8
complete -c intelligentroutingd -s a -d 'Description of -a flag'
complete -c intelligentroutingd -s b -d 'Description of -b flag \\" Ends the list FILES                \\" File used or …'

