# irb
# Autogenerated from man page /usr/share/man/man1/irb.1
complete -c irb -l version -d 'Prints the version of irb'
complete -c irb -s E
complete -c irb -l encoding -d 'Same as `ruby -E\' '
complete -c irb -s I -d 'Same as `ruby -I\' .  Specifies $LOAD_PATH directory'
complete -c irb -s U -d 'Same as `ruby -U\' '
complete -c irb -s d -d 'Same as `ruby -d\' .  Sets $DEBUG to true'
complete -c irb -s f -d 'Suppresses read of ~/. irbrc'
complete -c irb -s h
complete -c irb -l help -d 'Prints a summary of the options'
complete -c irb -s r -d 'Same as `ruby -r\'.  Causes irb to load the library using require'
complete -c irb -l inspect -d 'Uses `inspect\' for output (default except for bc mode)'
complete -c irb -l noinspect -d 'Doesn\'t use inspect for output'
complete -c irb -l readline -d 'Uses Readline extension module'
complete -c irb -l noreadline -d 'Doesn\'t use Readline extension module'
complete -c irb -l prompt
complete -c irb -l prompt-mode -d 'Switch prompt mode'
complete -c irb -l inf-ruby-mode -d 'Uses prompt appropriate for inf-ruby-mode on emacs.  Suppresses --readline'
complete -c irb -l simple-prompt -d 'Makes prompts simple'
complete -c irb -l noprompt -d 'No prompt mode'
complete -c irb -l tracer -d 'Displays trace for each execution of commands'
complete -c irb -l back-trace-limit -d 'Displays backtrace top n and tail n Ns.  The default value is 16'
complete -c irb -l irb_debug -d 'Sets internal debug level to n (not for popular use) El ENVIRONMENT -tag -com…'

