# ircbug
# Autogenerated from man page /opt/homebrew/share/man/man1/ircbug.1
complete -c ircbug -s f -d 'specify a file (problem-report) which already contains a complete problem rep…'
complete -c ircbug -s s -d 'Give the problem report the severity R severity '
complete -c ircbug -s t -d 'Change mail address at the support site for problem reports'
complete -c ircbug -s c -d 'Put  address in the   Cc: header of the message'
complete -c ircbug -s P -d 'print the form specified by the environment variable   PR_FORM  on standard o…'
complete -c ircbug -s L -d 'print the list of available categories.   No mail is sent'
complete -c ircbug -l request-id -d 'sends mail to the default support site, or  site if specified, with a request…'
complete -c ircbug -s v -d 'Display the  send-pr version number'

