# matchTool
# Autogenerated from man page /usr/share/man/man1/matchTool.1
complete -c matchTool -s a -d 'Description of -a flag'
complete -c matchTool -s b -d 'Description of -b flag \\" Ends the list FILES                \\" File used or …'

