# milod
# Autogenerated from man page /usr/share/man/man8/milod.8
complete -c milod -s a -d 'Description of -a flag'
complete -c milod -s b -d 'Description of -b flag \\" Ends the list FILES                \\" File used or …'

