# msdos.util
# Autogenerated from man page /usr/share/man/man8/msdos.util.8
complete -c 'msdos.util' -s m -d mount
complete -c 'msdos.util' -s n -d 'set name'
complete -c 'msdos.util' -s p -d 'probe for mounting'
complete -c 'msdos.util' -s u -d unmount
complete -c 'msdos.util' -s k -d 'print volume UUID El mountflags above are either: -bullet -compact -offset in…'

