# ndiff
# Autogenerated from man page /usr/local/share/man/man1/ndiff.1
complete -c ndiff -o sV -d 'oc o 2. 3'
complete -c ndiff -s O -d 'oc o 2. 3'
complete -c ndiff -s h -l help
complete -c ndiff -s v -l verbose
complete -c ndiff -l text
complete -c ndiff -l xml
complete -c ndiff -o Nmap -d '+Nmap 5. 35DC1 at 2010-07-16 12:13'
complete -c ndiff -o Not -d '+Not shown: 993 filtered ports  PORT      STATE  SERVICE VERSION  22/tcp    o…'
complete -c ndiff -s F -d 'fast scan option found two additional ports: 70 and 31337'
complete -c ndiff -o 80/tcp -d '+80/tcp open  http    lighttpd 1. 5. 0'
complete -c ndiff -o 'cm.out.snc1.tfbnw.net' -d '+mailout-snc1. facebook. com (69. 63. 179. 25):  Host is up'

