# networkQuality
# Autogenerated from man page /usr/share/man/man8/networkQuality.8
complete -c networkQuality -s b -d 'Show Bonjour advertised networkQuality servers'
complete -c networkQuality -s B -d 'Run against specified Bonjour instance'
complete -c networkQuality -s C -d 'Use custom configuration URL or path (with scheme file://)'
complete -c networkQuality -s f -d 'Force usage of a specific protocol selection: br h1: To enforce HTTP/1'
complete -c networkQuality -s I -d 'Bind test to interface (e. g. , en0, pdp_ip0,'
complete -c networkQuality -s r -d 'Connect to host or IP, overriding DNS for initial config request'
complete -c networkQuality -s S -d 'Create a networkQuality server-instance running locally on the specified port'
complete -c networkQuality -s c -d 'Produce computer-readable output (JSON)'
complete -c networkQuality -s d -d 'Do not run a download test (implies -s)'
complete -c networkQuality -s h -d 'Show help'
complete -c networkQuality -s k -d 'Disable verification of the server identity via TLS'
complete -c networkQuality -s p -d 'Use iCloud Private Relay'
complete -c networkQuality -s s -d 'Run tests sequentially instead of parallel upload/download'
complete -c networkQuality -s u -d 'Do not run an upload test (implies -s)'
complete -c networkQuality -s v -d 'Verbose output'

