# nfs4mapid
# Autogenerated from man page /usr/share/man/man8/nfs4mapid.8
complete -c nfs4mapid -s G -d 'Map an NFSv4 string to a gid'
complete -c nfs4mapid -s u -d 'Map a uid to an NFSv4 user@domain string'
complete -c nfs4mapid -s g -d 'Map a gid to an NFSv4 group@domain string'

