# nginx
# Autogenerated from man page /opt/homebrew/share/man/man8/nginx.8
complete -c nginx -s '?' -d 'Print help'
complete -c nginx -s c -d 'Use an alternative configuration file'
complete -c nginx -s e -d 'Use an alternative error log file'
complete -c nginx -s g -d 'Set global configuration directives.  See EXAMPLES for details'
complete -c nginx -s p -d 'Set the prefix path.  The default value is %%PREFIX%%'
complete -c nginx -s q -d 'Suppress non-error messages during configuration testing'
complete -c nginx -s s -d 'Send a signal to the master process'
complete -c nginx -s T -d 'Same as t, but additionally dump configuration files to standard output'
complete -c nginx -s t -d 'Do not run, just test the configuration file'
complete -c nginx -s V -d 'Print the nginx version, compiler version, and configure script parameters'
complete -c nginx -s v -d 'Print the nginx version'

