# osalang
# Autogenerated from man page /usr/share/man/man1/osalang.1
complete -c osalang -s d -d 'Only print the default language'
complete -c osalang -s l -d 'List in long format'
complete -c osalang -s L -d 'Same as l, but also prints the description of each component after its name'

