# photosctl
# Autogenerated from man page /usr/share/man/man1/photosctl.1
complete -c photosctl -s h -l help -d 'Convenience alias for help,'
complete -c photosctl -l version -d 'Show the version of photosctl'

