# pipes.sh
# Autogenerated from man page /opt/homebrew/share/man/man6/pipes.sh.6
complete -c 'pipes.sh' -s p -d 'Number of pipes.  (default is 1)'
complete -c 'pipes.sh' -s t -d 'Determines the type of pipes to be drawn.  Multiple arguments can be used'
complete -c 'pipes.sh' -s c -d 'Colors of pipes.  Multiple arguments can be used'
complete -c 'pipes.sh' -s f -d 'Frame rate.  (default is 75)'
complete -c 'pipes.sh' -s s -d 'Probability of straight fitting.  (default is 13)'
complete -c 'pipes.sh' -s r -d 'Resets the drawing after [LIMIT] characters'
complete -c 'pipes.sh' -s R -d 'Randomize starting position and direction'
complete -c 'pipes.sh' -s B -d 'No bold effect'
complete -c 'pipes.sh' -s C -d 'No color'
complete -c 'pipes.sh' -s K -d 'No change of colors and types when hitting screen edges'
complete -c 'pipes.sh' -s h -d 'Displays a help message'
complete -c 'pipes.sh' -s v -d 'Prints the version number'

