# ps2pdf13
# Autogenerated from man page /opt/homebrew/share/man/man1/ps2pdf13.1
complete -c ps2pdf13 -o dCompatibilityLevel -d 'switch in the command line'
complete -c ps2pdf13 -o dPDFSETTINGS -d 'figure. ps proof. pdf'
complete -c ps2pdf13 -s t -d ps2pdf

