# reboot
# Autogenerated from man page /usr/share/man/man8/reboot.8
complete -c reboot -s l -d 'The halt or reboot is not logged to the system log'
complete -c reboot -s N -d 'The file system cache is not flushed during the initial process clean-up, how…'
complete -c reboot -s n -d 'The file system cache is not flushed'
complete -c reboot -s q -d 'The system is halted or restarted quickly and ungracefully, and only the flus…'

