# remindd
# Autogenerated from man page /usr/share/man/man8/remindd.8
complete -c remindd -s a -d 'Description of -a flag'
complete -c remindd -s b -d 'Description of -b flag \\" Ends the list FILES                \\" File used or …'

