# reset
# Autogenerated from man page /usr/share/man/man1/reset.1
complete -c reset -o Ttype -d 'indicates the type of terminal'
complete -c reset -s S -d 'allows more than one capability per invocation of tput'
complete -c reset -s V -d 'reports the version of ncurses which was used in this program, and exits'

