# shazam-signature
# Autogenerated from man page /usr/share/man/man1/shazam-signature.1
complete -c shazam-signature -s i -l input -d 'Path to an audio or video file to generate a shazam signature from'
complete -c shazam-signature -s o -l start -d 'Apply a starting offset, in seconds, to skip unwanted audio at the beginning …'
complete -c shazam-signature -l duration -d 'Duration, in seconds, for each of the sliced signatures'
complete -c shazam-signature -l stride -d 'Separation, in seconds, between consecutive slices'
complete -c shazam-signature -l output -d 'Path to save the new shazam signature file'

