# sketchybar
# Autogenerated from man page /opt/homebrew/share/man/man1/sketchybar.1
complete -c sketchybar -l reload -d 'Reload the bar without manually restarting the process.  Essentially, this'
complete -c sketchybar -l hotload -d 'Enables the hotload feature.  If you wish that the bar automatically reloads'

