# smicache
# Autogenerated from man page /opt/homebrew/share/man/man1/smicache.1
complete -c smicache -s V -d 'Show the smicache version and exit'
complete -c smicache -s h -d 'Show a help text and exit'
complete -c smicache -s d -d 'Write fetched module file(s) to directory dir'
complete -c smicache -s p -d 'Use the URL prefix prefix for fetching modules'

