# smidiff
# Autogenerated from man page /opt/homebrew/share/man/man1/smidiff.1
complete -c smidiff -s V -l version -d 'Show the smidump version and exit'
complete -c smidiff -s h -l help -d 'Show a help text and exit'
complete -c smidiff -s s -l severity -d 'Show the error severity in brackets before error messages'
complete -c smidiff -s m -l error-names -d 'Show the error names in braces before error messages'
complete -c smidiff -s c -l config -d 'Read file instead of any other (global and user) configuration file'
complete -c smidiff -s p -l preload -d 'Preload the module module before reading the main module(s)'
complete -c smidiff -s l -l level -d 'Report errors and warnings up to the given severity level'
complete -c smidiff -s i -l ignore -d 'Ignore all errors that have a tag which matches prefix'

