# smidump
# Autogenerated from man page /opt/homebrew/share/man/man1/smidump.1
complete -c smidump -s V -l version -d 'Show the smidump version and exit'
complete -c smidump -s h -l help -d 'Show a help text and exit'
complete -c smidump -s c -l config -d 'Read file instead of any other (global and user) configuration file'
complete -c smidump -s f -l format -d 'Use format when dumping a module'
complete -c smidump -s l -l level -d 'Report errors and warnings up to the given severity level'
complete -c smidump -s s -l severity -d 'Show the error severity in brackets before error messages'
complete -c smidump -s m -l error-names -d 'Show the error names in braces before error messages'
complete -c smidump -s o -l output -d 'Write the output in one or multiple files instead of stdout'
complete -c smidump -s p -l preload -d 'Preload the module module before reading the main module(s)'
complete -c smidump -s q -l quiet -d 'Suppress comments from dumped modules'
complete -c smidump -s u -l unified -d 'Dump a unified output in case of multiple module(s) instead of multiple conca…'
complete -c smidump -s k -l keep-going -d 'Continue as much as possible after serious parse errors'

