# smilint
# Autogenerated from man page /opt/homebrew/share/man/man1/smilint.1
complete -c smilint -s V -l version -d 'Show the smilint version and exit'
complete -c smilint -s h -l help -d 'Show a help text and exit'
complete -c smilint -s e -l error-list -d 'Show a list of all known error messages and exit'
complete -c smilint -s r -l recursive -d 'Report errors and warnings also for recursively imported modules'
complete -c smilint -s s -l severity -d 'Show the error severity in brackets before error messages'
complete -c smilint -s m -l error-names -d 'Show the error names in braces before error messages'
complete -c smilint -s c -l config -d 'Read file instead of any other (global and user) configuration file'
complete -c smilint -s p -l preload -d 'Preload the module module before reading the main module(s)'
complete -c smilint -s l -l level -d 'Report errors and warnings up to the given severity level'
complete -c smilint -s i -l ignore -d 'Ignore all errors that have a tag which matches prefix'

