# smiquery
# Autogenerated from man page /opt/homebrew/share/man/man1/smiquery.1
complete -c smiquery -s V -l version -d 'Show the smiquery version and exit'
complete -c smiquery -s h -l help -d 'Show a help text and exit.  The help text lists all available commands'
complete -c smiquery -s p -l preload -d 'Preload the module module before reading the main module'

