# smistrip
# Autogenerated from man page /opt/homebrew/share/man/man1/smistrip.1
complete -c smistrip -s V -d 'Show the smistrip version and exit'
complete -c smistrip -s h -d 'Show a help text and exit'
complete -c smistrip -s n -d 'Print only what would be extracted, but do not write any output file'
complete -c smistrip -s d -d 'Write module file(s) to directory dir instead of the current working directory'
complete -c smistrip -s m -d 'Extract only the module module instead of all modules found in the input file…'

