# smixlate
# Autogenerated from man page /opt/homebrew/share/man/man1/smixlate.1
complete -c smixlate -s V -l version -d 'Show the smixlate version and exit'
complete -c smixlate -s h -l help -d 'Show a help text and exit'
complete -c smixlate -s r -l recursive -d 'Report errors and warnings also for recursively imported modules'
complete -c smixlate -s c -l config -d 'Read file instead of any other (global and user) configuration file'
complete -c smixlate -s p -l preload -d 'Preload the module module before reading the main module(s)'
complete -c smixlate -s l -l level -d 'Report errors and warnings up to the given severity level'
complete -c smixlate -s a -l all -d 'Replace all OIDs including OID prefixes'
complete -c smixlate -s f -l format -d 'Preserve the input format as much as possible by inserting/removing white spa…'

