# smtpd
# Autogenerated from man page /usr/share/man/man8/smtpd.8
complete -c smtpd -o bs -d '$mail_owner privileges, it receives mail even while the mail system is not ru…'
complete -c smtpd -s V -d 'and later'

