# sudoreplay
# Autogenerated from man page /usr/share/man/man8/sudoreplay.8
complete -c sudoreplay -s d -d 'option) or fully qualified, beginning with a `/\' character'
complete -c sudoreplay -s n -d 'option is not specified, sudoreplay will operate interactively'
complete -c sudoreplay -l directory -d 'Store session logs in dir instead of the default, /var/log/sudo-io'
complete -c sudoreplay -s f -l filter -d 'Select which I/O type(s) to display'
complete -c sudoreplay -s F -l follow -d 'Enable “follow mode”'
complete -c sudoreplay -s h -l help -d 'Display a short help message to the standard output and exit'
complete -c sudoreplay -s l -l list -d 'Enable “list mode”'
complete -c sudoreplay -s m -l max-wait -d 'Specify an upper bound on how long to wait between key presses or output data'
complete -c sudoreplay -l non-interactive -d 'Do not prompt for user input or attempt to re-size the terminal'
complete -c sudoreplay -s R -l no-resize -d 'Do not attempt to re-size the terminal to match the terminal size of the sess…'
complete -c sudoreplay -s S -l suspend-wait -d 'Wait while the command was suspended'
complete -c sudoreplay -s s -l speed -d 'This option causes sudoreplay to adjust the number of seconds it will wait be…'
complete -c sudoreplay -s V -l version -d 'Print the sudoreplay versions version number and exit'

