# textunderstandingd
# Autogenerated from man page /usr/share/man/man1/textunderstandingd.1
complete -c textunderstandingd -s a -d 'Description of -a flag'
complete -c textunderstandingd -s b -d 'Description of -b flag \\" Ends the list FILES                \\" File used or …'

