# trash
# Autogenerated from man page /usr/share/man/man8/trash.8
complete -c trash -s h -d 'display usage information for the tool and exit'
complete -c trash -s v -d 'display more verbose status'
complete -c trash -s s -d 'exit with an error if any move to a trash folder fails El EXAMPLES In a direc…'

