# w
# Autogenerated from man page /usr/share/man/man1/w.1
complete -c w -l libxo -d 'Generate output via libxo 3 in a selection of different human and machine rea…'
complete -c w -s h -d 'Suppress the heading'
complete -c w -s i -d 'Output is sorted by idle time'
complete -c w -s n -d 'Do not attempt to resolve network addresses (normally w interprets addresses …'

