# wfa_ca
# Autogenerated from man page /usr/share/man/man1/wfa_ca.1
complete -c wfa_ca -s a -d 'Description of -a flag'
complete -c wfa_ca -s b -d 'Description of -b flag \\" Ends the list FILES                \\" File used or …'

