# wtf
# Autogenerated from man page /opt/homebrew/share/man/man6/wtf.6
complete -c wtf -s f -d 'Overrides the default list of acronym databases, bypassing the value of the A…'
complete -c wtf -s o -d 'Include acronyms that could be considered offensive to some'

